#DEVELOPER: LEANDRO CASTRO
#LINGUAGEM: PYTHON
#PROGRAMA QUE MOSTRA CONTAGEM REGRESSIVA DEO LANCAMENTO DE UM FOGUETE NO USA!!!

print('\n'"PROGRAMA QUE MOSTRA CONTAGEM REGRESSIVA DEO LANCAMENTO DE UM FOGUETE NO USA!!!")

x = 10
while x >= 0:
    print(x)
    x -= 1

print('\n'"FOOOOGOOOOOOO!!!!!!!!!!!!!!")
